# .github/workflows/playwright.yml
name: Playwright Tests

on:
  push:
    branches: [ dev ] # Trigger on push to the 'dev' branch
  pull_request:
    branches: [ dev ] # Trigger on pull request to the 'dev' branch
  schedule:
    # Run every day at 1 AM UTC
    # Learn more about cron syntax: https://docs.github.com/actions/reference/events#schedule
    - cron: '0 1 * * *'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

